CREATE TABLE anamnesis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customerId INTEGER,
    previousEstheticTreatment BOOLEAN,
    specifyPreviousEstheticTreatment TEXT,
    allergies BOOLEAN,
    specifyAllergies TEXT,
    regularIntestinalFunction BOOLEAN,
    specifyRegularIntestinalFunction TEXT,
    practiceSports BOOLEAN,
    specifyPracticeSports TEXT,
    balancedDiet BOOLEAN,
    specifyBalancedDiet TEXT,
    medicalTreatment BOOLEAN,
    specifyMedicalTreatment TEXT,
    useMedications BOOLEAN,
    specifyUseMedications TEXT,
    pacemaker BOOLEAN,
    specifyPacemaker TEXT,
    metalProstheses BOOLEAN,
    specifyMetalProstheses TEXT,
    heartProblems BOOLEAN,
    specifyHeartProblems TEXT,
    oncologicalHistory BOOLEAN,
    specifyOncologicalHistory TEXT,
    menstrualCycle BOOLEAN,
    specifyMenstrualCycle TEXT,
    contraceptiveMethod BOOLEAN,
    specifyContraceptiveMethod TEXT,
    dailyCareProducts BOOLEAN,
    specifyDailyCareProducts TEXT,
    pregnant BOOLEAN,
    hasChildren BOOLEAN,
    childrenQuantity INTEGER,
    smoke BOOLEAN,
    epilepsy BOOLEAN,
    diabetes BOOLEAN,
    dentalProsthesis BOOLEAN,
    sunExposure BOOLEAN,
    hypertensive BOOLEAN,
    FOREIGN KEY (customerId) REFERENCES customers(id)
);
