SELECT
    c.id AS customerId,
    c.name,
    c.rg,
    c.cpf,
    c.address,
    c.cep,
    c.city,
    c.email,
    c.phone1,
    c.phone2,
    c.birthDate,
    a.id AS anamnesisId,
    a.previousEstheticTreatment,
    a.specifyPreviousEstheticTreatment,
    a.allergies,
    a.specifyAllergies,
    a.regularIntestinalFunction,
    a.specifyRegularIntestinalFunction,
    a.practiceSports,
    a.specifyPracticeSports,
    a.balancedDiet,
    a.specifyBalancedDiet,
    a.medicalTreatment,
    a.specifyMedicalTreatment,
    a.useMedications,
    a.specifyUseMedications,
    a.pacemaker,
    a.specifyPacemaker,
    a.metalProstheses,
    a.specifyMetalProstheses,
    a.heartProblems,
    a.specifyHeartProblems,
    a.oncologicalHistory,
    a.specifyOncologicalHistory,
    a.menstrualCycle,
    a.specifyMenstrualCycle,
    a.contraceptiveMethod,
    a.specifyContraceptiveMethod,
    a.dailyCareProducts,
    a.specifyDailyCareProducts,
    a.pregnant,
    a.hasChildren,
    a.childrenQuantity,
    a.smoke,
    a.epilepsy,
    a.diabetes,
    a.dentalProsthesis,
    a.sunExposure,
    a.hypertensive
FROM
    customers c
LEFT JOIN
    anamnesis a
ON
    c.id = a.customerId;
